### ISSUE TITLE
Deadlock if port has self-reference

### ISSUE THREAD

**Issue by lesomnus** [lesomnus/clade#26]
`clade tree` does not end if _port_ has self-reference.
e.g.
```yaml
images:
  - tags:
      - ( printf "%d.%d.%d" $.Major $.Minor $.Patch )
      - ( printf "%d.%d"    $.Major $.Minor         )
    from:
      name: mcr.microsoft.com/dotnet/sdk
      tag: ( tags | semverFinalized | semverN 1 1 2 )

  - tags:
      - ( printf "%d.%d.%d-android" $.Major $.Minor $.Patch )
      - ( printf "%d.%d-android"    $.Major $.Minor         )
    from:
      name: ghcr.io/lesomnus/dev-dotnet
      tag: ( tags | semver )
```
