### ISSUE TITLE
pipeline expression on `args`

### ISSUE THREAD

**Issue by lesomnus** [lesomnus/clade#37]
e.g.
```yaml
images:
  - tags:
      - ( printf "%d.%d" $.Major $.Minor )
      - ( printf "%d"    $.Major         )
    from:
      name: registry.hub.docker.com/library/gcc
      tag: ( tags | semverFinalized | semverN 2 2 0 )
    args:
      VERSION: ( printf "%d.%d" $.Major $.Minor )  # <-
```
