### ISSUE TITLE
If the image is based on a different image than the one in the port file, it is always outdated.

### ISSUE THREAD

**Issue by lesomnus** [lesomnus/clade#41]
```yaml
...
    from:
      name: registry.hub.docker.com/library/docker
...
```
```Dockerfile
FROM registry.hub.docker.com/library/debian:${DEBIAN_TAG}
...
```

The dockerfile does not based on the `registry.hub.docker.com/library/docker` so it is always outdated since there is no common layers in images.
